version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=cloudwatch,logs,iam,s3,dynamodb,lambda
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
    volumes:
      - ./localstack-data:/var/lib/localstack
