apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    jsonData:
      timeField: "@timestamp"
      index: "service-logs-*"
      logMessageField: "message"     # ✅ tells Grafana what to show as log text
      logLevelField: "level.keyword" # ✅ required for level-based color coding (optional but ideal)
